apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeadm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kubeadm-master
  template:
    metadata:
      labels:
        component: kubeadm-master
    spec:
      containers:
        - name: kubeadm-master
          image: joshshih/mytestgo:v01
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeadm-svc
spec:
  type: NodePort
  selector: 
    component: kubeadm-master
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002