apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sqlbackup-deployment
  labels:
    app: aws-sqlbackup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sqlbackup
  template:
    metadata:
      labels:
        app: aws-sqlbackup
    spec:
      containers:
        - name: aws-sqlbackup
          image: joshshih/aws-sqlbackup:v05
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: ACCESS_KEY_ID
              value: ""
            - name: SECRET_ACCSS_KEY
              value: ""
          command:
            - sleep
            - "3600"
            # - export PATH="$PATH:$HOME/.local/bin"
            # - /bin/sh
            # - -c
            # - |
            #   export PATH=$PATH:$HOME/.local/bin
