# a cluster with 1 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    extraMounts:
      - hostPath: /home/sv/kind_data/k_mysql
        containerPath: /k_mysql
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        # protocol: udp # Optional, defaults to tcp
        protocol: TCP # Optional, defaults to tcp
      - containerPort: 30001
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30002
        hostPort: 15021
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 32192
        hostPort: 32192
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    extraMounts:
      - hostPath: /home/sv/kind_data/k_mysql
        containerPath: /k_mysql
  - role: worker
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    extraMounts:
      - hostPath: /home/sv/kind_data/k_mysql
        containerPath: /k_mysql
  - role: worker
    image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
    extraMounts:
      - hostPath: /home/sv/kind_data/k_mysql
        containerPath: /k_mysql
