apiVersion: v1
kind: Service
metadata:
  name: mongocfg1
  namespace: mongoshard
  labels:
    app: mongocfg1
spec:
  ports:
    - port: 27019
      protocol: TCP
  selector:
    app: mongocfg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocfg1
  namespace: mongoshard
spec:
  replicas: 1
  selector:
    app: mongocfg1
  template:
    metadata:
      labels:
        name: mongocfg1
        app: mongocfg1
    spec:
      restartPolicy: Always
      hostname: mongocfg1
      containers:
        - image: mongo:latest
          name: mongocfg1
          ports:
            - name: mongocfg1
              containerPort: 27019
          volumeMounts:
            - name: mongocfg1
              mountPath: /data/db
          command: ["mongod"]
          args:
            [
              "--noprealloc",
              "--smallfiles",
              "--replSet",
              "cfgrs",
              "--dbpath",
              "/data/db",
              "--configsvr",
              "--noauth",
              "--bind_ip_all",
            ]
      volumes:
        - name: mongocfg1
          #persistentVolumeClaim:
          #  claimName: mongocfg1
