apiVersion: v1
kind: Service
metadata:
  name: mongocfg1
  labels:
    run: mongocfg1
    component: mongocfg1
spec:
  ports:
    - port: 27019
      protocol: TCP
  selector:
    run: mongocfg1
    component: mongocfg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocfg1
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongocfg1
      run: mongocfg1
  template:
    metadata:
      labels:
        name: mongocfg1
        run: mongocfg1
        component: mongocfg1
    spec:
      restartPolicy: Always
      hostname: mongocfg1
      containers:
        - image: mongo:4.4.2
          name: mongocfg1
          ports:
            - name: mongocfg1
              containerPort: 27019
          volumeMounts:
            - name: mongocfg1
              mountPath: /data/db
          command: ["mongod"]
          args:
            [
              "--noprealloc",
              "--smallfiles",
              "--replSet",
              "cfgrs",
              "--dbpath",
              "/data/db",
              "--configsvr",
              "--noauth",
              "--bind_ip_all",
            ]
      # volumes:
      #   - name: mongocfg1
      #     #persistentVolumeClaim:
      #     #  claimName: mongocfg1
