apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongocfg1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.172.199
    path: "/var/nfsshare/kubeadm/redis_cluster/redis0/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongocfg1-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
