# Mongo shard replica set 3 node 1
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-1
  labels:
    run: mongosh3-1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh3-1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh3-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh3-1
        run: mongosh3-1
    spec:
      restartPolicy: Always
      hostname: mongosh3-1
      containers:
      - image: mongo:latest
        name: mongosh3-1
        ports:
        - name: mongosh3-1
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-1
              mountPath: /data/db
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--replSet", "rs3", "--dbpath","/data/db", "--noauth", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-1
          #persistentVolumeClaim:
          #  claimName: mongosh3-1
---
# Mongo shard replica set 3 node 2
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-2
  labels:
    run: mongosh3-2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh3-2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh3-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh3-2
        run: mongosh3-2
    spec:
      restartPolicy: Always
      hostname: mongosh3-2
      containers:
      - image: mongo:latest
        name: mongosh3-2
        ports:
        - name: mongosh3-2
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-2
              mountPath: /data/db
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--replSet", "rs3", "--dbpath","/data/db", "--noauth", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-2
          #persistentVolumeClaim:
          #  claimName: mongosh3-2
---
# Mongo shard replica set 3 node 3
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-3
  labels:
    run: mongosh3-3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh3-3
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh3-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh3-3
        run: mongosh3-3
    spec:
      restartPolicy: Always
      hostname: mongosh3-3
      containers:
      - image: mongo:latest
        name: mongosh3-3
        ports:
        - name: mongosh3-3
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-3
              mountPath: /data/db
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--replSet", "rs3", "--dbpath","/data/db", "--noauth", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-3
          #persistentVolumeClaim:
          #  claimName: mongosh3-3
