version: '3.0'
services:
  mariadbspider:
    restart: always
    image: "mariadb:10.7"
    ports:
      - "33064:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    links:
      - mariadb_1
      - mariadb_2
      - mariadb_3
  mariadb_1:
    restart: always
    image: "mariadb:10.7"
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  mariadb_2:
    restart: always
    image: "mariadb:10.7"
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  mariadb_3:
    restart: always
    image: "mariadb:10.7"
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456