version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG= 1
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=dev
      - DB_USER=dev
      - DB_PASS=123456
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost 
      - MYSQL_PORT=3306 
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8800:80'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306