apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-router-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.172.199
    path: "/var/nfsshare/dev/sharded/data/router/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hs-router-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
