apiVersion: v1
kind: Service
metadata:
  name: config2-svc
spec:
  type: ClusterIP
  selector:
    component: mongo-config2
  ports:
    - port: 27019
      targetPort: 27019
      name: config2
      protocol: TCP
    - port: 27017
      targetPort: 27017
      name: config22
      protocol: TCP
    - port: 27018
      targetPort: 27018
      name: config222
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-config2
  name: mongo-config2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo-config2
  template:
    metadata:
      labels:
        component: mongo-config2
    spec:
      containers:
        - name: mongo-config2
          image: mongo:4.4.2 # mongo:5.0
          # command:
          #   - mongod
          #   - "--configsvr"
          #   - "--replSet"
          #   - Config
          #   - "--bind_ip"
          #   - 0.0.0.0
          command: ["mongod"]
          args: [
              # "--noprealloc",
              # "--smallfiles",
              "--replSet",
              "Config",
              "--dbpath",
              "/data/db",
              "--configsvr",
              "--noauth",
              # "--bind_ip_all",
              "--bind_ip",
              "0.0.0.0",
            ]
          ports:
            - containerPort: 27019
            - containerPort: 27017
            - containerPort: 27018
          volumeMounts:
            - name: mongo-config2-storage
              mountPath: /data/db
      volumes:
        - name: mongo-config2-storage
          persistentVolumeClaim:
            claimName: hs-config2-pvc
