apiVersion: v1
kind: Service
metadata:
  name: router-svc
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    component: mongo-router
  ports:
    # - port: 27019
    #   targetPort: 27019
    #   name: router
    #   protocol: TCP
    - port: 27017
      targetPort: 27017
      nodePort: 30700
      name: router1
      protocol: TCP
    # - port: 27017
    #   targetPort: 27017
    #   name: router1
    #   protocol: TCP
    # - port: 27018
    #   targetPort: 27018
    #   name: router11
    #   protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-router
  name: mongo-router
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo-router
  template:
    metadata:
      labels:
        component: mongo-router
    spec:
      containers:
        - name: mongo-router
          image: mongo:4.4.2 # mongo:5.0
          # command:
          #   - mongod
          #   - "--configsvr"
          #   - "--replSet"
          #   - Config
          #   - "--bind_ip"
          #   - 0.0.0.0
          command: ["mongos"]
          args:
            [
              "--configdb",
              "Config/config1-svc:27019,config2-svc:27019,config3-svc:27019",
              "--bind_ip",
              "0.0.0.0",
            ]
            # [
            #   "--configdb",
            #   "Config/config1-svc:27018,config2-svc:27018,config3-svc:27018",
            #   # "--noauth",
            #   "--bind_ip",
            #   "0.0.0.0",
            # ]
          ports:
            - containerPort: 27019
            - containerPort: 27017
            - containerPort: 27018
          volumeMounts:
            - name: mongo-router-storage
              mountPath: /data/db
      volumes:
        - name: mongo-router-storage
          persistentVolumeClaim:
            claimName: hs-router-pvc
