apiVersion: v1
kind: Service
metadata:
  name: mongodbroutersvc
  labels:
    name: mongorouter
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongorouter
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongosrouter
spec:
  selector:
    matchLabels:
      role: mongorouter
  serviceName: mongodbroutersvc
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongorouter
        replicaset: mongorouters
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongorouters
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongosroutercontainer
          image: mongo:3.6.2
          command:
            - "numactl"
            - "--interleave=all"
            - "mongos"
            - "--configdb"            
            - "mongoreplicaset1config/mongodbconfigstateful-0.mongodbconfigservice.default.svc.cluster.local:27017,mongodbconfigstateful-1.mongodbconfigservice.default.svc.cluster.local:27017,mongodbconfigstateful-2.mongodbconfigservice.default.svc.cluster.local:27017"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.getMongo()"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 60
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.getMongo()"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 60
            failureThreshold: 6
