global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['192.168.172.203:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.93.132:9100'] ## IP Address of the localho
        labels:
          host: 'localhost'
      - targets: ['192.168.172.203:9100']
        labels:
          host: 'sv-server'